### ISSUE TITLE
Please add example on how to specify output format

### ISSUE THREAD

**Issue by UGuntupalli** [dadadel/pyment#102]
Hello, 
     Thanks for the work in putting this great package together. I just came across it today and I really like it. I have a python project where all my docstrings are restructured text format. I was unable to find an example that shows how to specify the output format for the docstring conversion. Could you kindly share an example ? 

Thanks

**Comment by dkdndes** [comment]
Please read the documentation, the parameter is

`-o style, --output style`

the style options are explained [here](https://github.com/dadadel/pyment/blob/master/doc/sphinx/source/pyment.rst).
