### ISSUE TITLE
option to write back the files instead of making patches

### ISSUE THREAD

**Issue by eastein** [dadadel/pyment#20]
The way this is done in autopep8 could be a good guide to doing this.  There are certainly cases where generating patches is useful, but with everyone using git these days, it's very easy to keep the old version of things and use "git diff" if you want to see the changes before committing them, rather than having to apply them all with patch.

**Comment by eastein** [comment]
PR here - please merge :) 

https://github.com/dadadel/pyment/pull/21

**Comment by dadadel** [comment]
Sorry @eastein for being so long to check your PR. Thanks for your help.

**Comment by eastein** [comment]
Thanks for the merge and the cool tool!

**Comment by jonfitt** [comment]
@eastein @dadadel 
On Windows the -w option gives a 'File already exists' error. Am I  using this wrong, or does it need a new issue opened?
```
pyment -w soapInterface.py

Traceback (most recent call last):
  File "c:\python34\scripts\pyment-script.py", line 9, in <module>
    load_entry_point('Pyment==0.3.2.dev0', 'console_scripts', 'pyment')()
  File "c:\python34\lib\site-packages\pyment-0.3.2.dev0-py3.4.egg\pyment\pymentapp.py", line 149, in main
  File "c:\python34\lib\site-packages\pyment-0.3.2.dev0-py3.4.egg\pyment\pymentapp.py", line 103, in run
  File "c:\python34\lib\site-packages\pyment-0.3.2.dev0-py3.4.egg\pyment\pyment.py", line 320, in write_to_file
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'soapInterface.py.writing' -> 'soapInterface.py'
```

**Comment by eastein** [comment]
You are right to comment here @jonfitt, it is related to this. I did not realize that `os.rename` does not work when the target exists already for the target on Windows - I don't use windows and forgot to consider how my changes would affect windows users.

I wrote that file writer code with the intention of making sure that file loss was very unlikely (ensuring that I could write the whole output before removing the pre-modification source file) and renaming.

http://stackoverflow.com/a/35202735 goes into this a bit. Perhaps a new bug issue is needed as this bug exists in a released version of pyment.

**Comment by eastein** [comment]
https://github.com/dadadel/pyment/issues/26 it looks like someone else has this problem too...

**Comment by asettouf** [comment]
Why not simply adding the following?

```
import platform
if platform.system() == "Windows":
    os.remove(self.input_file) if os.path.isfile(self.input_file) else None
```

**Comment by eastein** [comment]
@asettouf I suggest that you put that code in a pull request for issue #26 which is an open bug for this problem - seems fine to me to do it that way.

**Comment by dadadel** [comment]
For information, the PR #40 was merged and should resolve the problem under Windows.
