### ISSUE TITLE
Class __init__() docstrings are not generated

### ISSUE THREAD

**Issue by alcazoid** [dadadel/pyment#22]
Hi,
when I'm generating docstrings on the file that have them missing, no docstring for **init**() in the classes is getting generated.
I'm running pyments with default settings.

**Comment by graik** [comment]
A related problem: also with setting -t. __init__ doc strings that are present, are not being converted.

**Comment by dadadel** [comment]
It seems indeed fixed, as shown by the new test.

**Comment by MariusMeiners** [comment]
apprently this issue is not solved - i just ran into this
