### ISSUE TITLE
 WindowsError: [Error 183] Can not create a file that already exists

### ISSUE THREAD

**Issue by kkloos** [dadadel/pyment#26]
When pathing a file on windows (or directly modifying it) python throws  "WindowsError: [Error 183] Can not create a file that already exists".

I could fix the problem myself by deleting the orignal file before renaming the temporal file in the write_to_file method. I just added os.remove(self.input_file) in line 320 in pyment.py.

I also encountered an end-of line issue (each line end was doubled in Spyder), but I could fix it with the pull request #25 by yoongu. 

Anyhow, thanks for the great package, it works fine for me - at least after those changes.

**Comment by dadadel** [comment]
Thanks to have pointed that problem. The PR #40 was merged and should fix the problem.
