### ISSUE TITLE
Add to pypi

### ISSUE THREAD

**Issue by cbillingham** [dadadel/pyment#37]
This is a super useful tool for updating old codebases to new standards! Thanks for developing it. It would be great to add this package to pypi!

**Comment by asettouf** [comment]
I'll take this task if no one minds

**Comment by dadadel** [comment]
Hi @cbillingham,
I planned to add Pyment to Pypi but I wanted to realese a new version fixing some issues before doing so.
However, thanks for preparing this.

**Comment by Code-ReaQtor** [comment]
@dadadel When is the target pypi release? It's 2018 in a few days! :)

Cheers!

**Comment by dkdndes** [comment]
Sure you know it but just in case: 

* https://packaging.python.org/tutorials/packaging-projects/

**Comment by alok** [comment]
@dadadel This would be nice to have as an "official" pip-installable package.

**Comment by dadadel** [comment]
Hi @asettouf ,

Could you give me ([dadel](https://test.pypi.org/user/dadel/)) rights to [pyment](https://test.pypi.org/project/Pyment/) in Pypi test.

Best

**Comment by asettouf** [comment]
Hi @dadadel ,

it's done. Can you check that you have the owner rights?

**Comment by dadadel** [comment]
@asettouf 
Thank you, I was able to upload to test Pypi. But I wasn't able to Pypi. Have you the rights on Pypi also ?

**Comment by asettouf** [comment]
@dadadel 
There is no pyment on Pypi yet, so no I have no rights on it there. Normally you should be able to upload it there without any actions from my side.

You might have to create an account there in addition of PypiTest though.

**Comment by dadadel** [comment]
@asettouf 
Yes I have an account on Pyment. But Pyment has already been create once a time by meyt for another project before removing it. In [that issue](https://github.com/meyt/payit/issues/1) he said that he gave the rights to you.

**Comment by asettouf** [comment]
@dadadel 

My bad for not following it closely, however here is what I have from pypi:

![pypi](https://user-images.githubusercontent.com/6400458/43227243-6e0946d2-905e-11e8-97c5-eff6c324548f.png)

I unfortunately have no way to manage anything there.

**Comment by dadadel** [comment]
@asettouf @dkdndes 
That's done!
Now Pyment is available on Pypi...
Better late than never :-)
