### ISSUE TITLE
STDIN support?

### ISSUE THREAD

**Issue by alok** [dadadel/pyment#53]
Just saw this, and I'd love to incorporate it into plugins like [neoformat](https://github.com/sbdchd/neoformat). It'd be nice if pyment could take in code via STDIN and output the newly formatted code (not a patch but just the updated code) via STDOUT. Essentially, the `-w` flag without actually overwriting a file.

**Comment by dadadel** [comment]
Hi @Alok,
This is a good idea indeed. Feel free to contribute if you can, else I'll try to find some time to do so.
Thanks for your issue.

**Comment by bryder** [comment]
I have submitted #59 to implement this.

**Comment by dadadel** [comment]
Thanks @alok for the suggestion and thanks @bryder for the implementation!

I close as it works well!

**Comment by dadadel** [comment]
As pointed out by @alok it sounds better if the output is actually the new version of the input instead of the patch.

**Comment by dadadel** [comment]
I think this issue can be closed as I reopened it for a bad reason!
If someone think the default behavior of Pyment should be changed so an other issue would be relevant.
