### ISSUE TITLE
Switch to ast module for docstring extraction 

### ISSUE THREAD

**Issue by wagnerpeer** [dadadel/pyment#61]
At the moment _pyment_ is parsing complete Python files on its own in a very basic way.

However parsing and extracting any information from Python files is naturally a built-in feature of the programming language.
For this I propose to use the [`ast`](https://docs.python.org/3/library/ast.html#ast) module and it's features of node visitors. See also:
   [`ast.NodeVisitor`](https://docs.python.org/3/library/ast.html#ast.NodeVisitor)
To extract docstrings one can use the function [`ast.get_docstring()`](https://docs.python.org/3/library/ast.html#ast.get_docstring). 

Another benefit would be the reliable identification of names, types and default values of function, class and method arguments. This would address issue #46 

In the long run, switching to the `ast` module would also allow to use  [`ast.NodeTransformer`](https://docs.python.org/3/library/ast.html#ast.NodeTransformer), which can be used to modify the ast in place, aka. modifying the docstrings in a more direct way.

**Comment by wagnerpeer** [comment]
The longer I think about my own proposal, I also think that there must be a better solution.

After I looked it up I have to admit, that the sphinx extension napoleon could be part of a solution. It enables sphinx to correctly parse the full Google Style Python docstrings definition as well as numpydoc and directly convert rhem to reST docstrings.

How about switching to sphinx to parse docstrings?

**Comment by dadadel** [comment]
Hi @wagnerpeer 
Thanks for your suggestion. Actually I considered *ast* at the begining and tried it but it didn't work well with the project I had to convert at the time, so I wen't in my own solution that fitted my needs.
When Pyment began to be more complex I thought about refactoring the code but I never had the time to do it. 
Now I think it could be indeed a goog thing to work on a more sustainable solution as you propose. Concerning Sphinx, I'd prefer to keep Pyment independent on external projects, but why not allow this via plugins.

**Comment by wagnerpeer** [comment]
Is there a place to discuss enhancements or should I open an issue for every idea I have?

How about directly via Mail or using the Wiki of the repository?

**Comment by dadadel** [comment]
I didn't think about a special way to address enhancements.
I don't know if a wiki is the good place, but perhaps creating issues with an adapted tag can be a good way. Or by mail if you wan't and if there is exchanges useless in public.
