### ISSUE TITLE
Confusing version strings

### ISSUE THREAD

**Issue by torfsen** [dadadel/pyment#77]
The latest release tag is [3.2.0](https://github.com/dadadel/pyment/releases/tag/v3.2.0), but `pyment.__version__` in that tag is still `0.3.2`:

https://github.com/dadadel/pyment/blob/0e55c9f7374b412c4014ff655270ba92f29ff344/pyment/pyment.py#L13

The latest version available from PyPI, on the other hand, [is 0.3.3](https://pypi.org/project/pyment/).

So that's 3 different version numbers, and it's totally confusing.

**Comment by dadadel** [comment]
Hi @torfsen ,
In master, the version is "0.3.3". Indeed the last tag has a bad version number 3.2.0 while it should be 0.3.2!
And I should release the 0.3.3 as last tag.
Thanks for reporting!

**Comment by dadadel** [comment]
FYI I have deleted tag v3.2.0 and added v0.3.2 on the same commit.
