### ISSUE TITLE
No patch is generated, only numbers are printed

### ISSUE THREAD

**Issue by torfsen** [dadadel/pyment#78]
When I run pyment against the provided [example.py](https://github.com/dadadel/pyment/blob/master/example.py) file, I don't get a patch output but only some numbers:

```
$ pyment example.py
49 50
```

The same happens for other files:
```
$ pyment one/of/my/files.py
3 3
15 17
19 20
23 24
```

I'm using version 0.3.3:
```
$ pyment --version
Pyment v0.3.3 - Copyright 2012-2018 - A. Daouzli - GPL3
```

**Comment by dadadel** [comment]
Hi @torfsen,
The shown numbers are not supposed to be printed, I guess a clean miss :)
However, by default Pyment generates a patch so when you run the command, the example.py.patch is generated (or overwritten). You'll have to use options to change the behaviour.

**Comment by torfsen** [comment]
Ah, thanks for the clarification! I was expecting output to go to STDOUT by default for some reason (the actual behavior is well-documented, so that's entirely my fault).

I've created a new ticket regarding output to STDOUT (#80), since that is what I was trying to do.
