### ISSUE TITLE
Add option for output to STDOUT

### ISSUE THREAD

**Issue by torfsen** [dadadel/pyment#80]
It seems that there is currently no option to output to STDOUT. That would be a nice feature in my opinion, since my usual workflow with tools like this is to first get a quick preview of the proposed changes on STDOUT (usually piped to `less`) and, if satisfied, apply the changes in-place. Of course I can do that using the generated `.patch` file, but it's more cumbersome. So I'd love to have a CLI parameter to redirect the output to STDOUT.

**Comment by dadadel** [comment]
@torfsen 
Thanks for suggestion, I think this was already asked in issue #53

**Comment by dadadel** [comment]
Note that if you provide `-` to pyment as path, it will take its input from stdin and provide its output to stdout.

**Comment by dadadel** [comment]
I close the issue as the stdout is available. If this doesn't really suit your use case, feel free to reopen the issue.
