### ISSUE TITLE
encoding error on windows

### ISSUE THREAD

**Issue by trim21** [dadadel/pyment#81]
I'm using pyment on windows with python3

All my python files are utf-8 encoded, and when I try to use it on my codes with CJK, I got `UnicodeDecodeError: 'gbk' codec can't decode byte 0xa5 in position 408: illegal multibyte sequence`

**Comment by Trim21** [comment]
https://github.com/dadadel/pyment/blob/3d1bdf87d083ff56230bd0bf7c5252e20552b7b6/pyment/pyment.py#L87-L97

Maybe `open(self.input_file, encoding='utf-8')`

**Comment by dadadel** [comment]
Hi @Trim21 
Thanks for reporting. Did you try the fix you suggested? And if so, did it work?

**Comment by dadadel** [comment]
Hi @Trim21 
Thanks for reporting. Did you try the fix you suggested? And if so, did it work?
Have you some code sample? When I have utf-8 in a script, I have no error. But I am on Linux.

**Comment by Trim21** [comment]
It's a little bit complicated. It works with python3 on windows if users are using utf-8 as encoding. But some users may use gbk as encoding, which is the default encoding when calling `open`.

I'm considering writing a package to detect python source file encoding for these problems.

**Comment by Trim21** [comment]
Oh. I was wondering why ci on windows passed all tests. Then I found that none of them include any CJK characters.

**Comment by codetin** [comment]
> Hi @Trim21
> Thanks for reporting. Did you try the fix you suggested? And if so, did it work?
> Have you some code sample? When I have utf-8 in a script, I have no error. But I am on Linux.

this patch works for me

**Comment by trim21** [comment]
this can be fixed by using PYTHONUTF8
