### ISSUE TITLE
When converting from reST, parameter types are not handled correctly

### ISSUE THREAD

**Issue by tikeyknax** [dadadel/pyment#85]
Using the command `pyment -o numpydoc -i reST -t -w input_file`, with the doc-string

    :param lxml.etree.ElementTree param_file: xml-element tree
        obtained from the file.
    :param str mask: Name of mask to be considered.

is converted to

    Parameters
    ----------
    lxml :
        etree.ElementTree param_file: xml-element tree
        obtained from the file.
    str :
        mask: Name of mask to be considered.

However, the expected output would be:

    Parameters
    ----------
    param_file : lxml.etree.ElementTree
        xml-element tree obtained from the file.
    mask : str
        Name of mask to be considered.

**Comment by Mattwmaster58** [comment]
I'd guess that the regex for a type only permits a single dot

**Comment by Jawabiscuit** [comment]
[related comment](https://github.com/dadadel/pyment/issues/86#issuecomment-611541588) on #86

**Comment by rwols** [comment]
I'm guessing this project needs a new maintainer?

**Comment by dadadel** [comment]
In reST the type is expected to be provided apart from the parameter description like:
```
:param param_file: xml-element tree
    obtained from the file.
:type param_file: lxml.etree.ElementTree
```
But this could be managed. I will try to work on it. Don't hesitate if you want to contribute.

**Comment by dadadel** [comment]
Hi @tikeyknax,
Can you tell me where did you see the usage of including the type in param statement for reST like in `:param lxml.etree.ElementTree param_file:`?

**Comment by Jawabiscuit** [comment]
It is common for writers of reST to be using documentation engines such as sphinx which is where I picked up the usage of [info fields list](https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#info-field-lists).

**Comment by tikeyknax** [comment]
Thanks for looking into this issue. If I understand the example correctly, when converting a docstring to numpy docstyle, the type is now completely lost? If that is the case, the change would unfortunately still not solve the issue.

**Comment by tikeyknax** [comment]
> ```diff
> -    :param lxml.etree.ElementTree param_file: xml-element tree
> +
> +    Parameters
> +    ----------
> +    param_file :
> +        xml-element tree
>          obtained from the file.
> -    :param str mask: Name of mask to be considered.
> +    mask :
> +        Name of mask to be considered.
> ```

I was refering to this example where the type of the variables seem to be lost. What I would have expected is:
```diff
-    :param lxml.etree.ElementTree param_file: xml-element tree
+
+    Parameters
+    ----------
+    param_file : lxml.etree.ElementTree
+        xml-element tree
         obtained from the file.
-    :param str mask: Name of mask to be considered.
+    mask : str
+        Name of mask to be considered.
 ```

**Comment by dadadel** [comment]
My bad @tikeyknax 
What I showed is not what is produced. I failed my copy/past ^^
Actually, Pyment does the job:
```diff
# Patch generated by Pyment v0.4.0dev

--- a/issue85.py
+++ b/issue85.py
@@ -1,58 +1,113 @@
 def func(param_file, mask):
     """
-    :param lxml.etree.ElementTree param_file: xml-element tree
+
+    Parameters
+    ----------
+    param_file : lxml.etree.ElementTree
+        xml-element tree
         obtained from the file.
-    :param str mask: Name of mask to be considered.
+    mask : str
+        Name of mask to be considered.
```
I have fixed also the example.

**Comment by tikeyknax** [comment]
Very nice. Thank you very much for fixing this issue. I'll definitely give this a try on our code base.
