### ISSUE TITLE
`return """something"""` is mistaken as docstring if it's at the first line of a function

### ISSUE THREAD

**Issue by spotlesstofu** [dadadel/pyment#87]
This:
```
    def __str__(self):
        return '''\
Autodiscover endpoint: %s
Auth type: %s''' % (
            self.service_endpoint,
            self.auth_type,
        )
```
becomes this (after running pyment):
```
    def __str__(self):
        """

        Args:

        Returns:
          Autodiscover endpoint: %s
          Auth type: %s''' % (

        """
            self.service_endpoint,
            self.auth_type,
        )
```
To replicate, run `pyment -o google -p False -t -w` on [this file](https://github.com/ecederstrand/exchangelib/blob/master/exchangelib/autodiscover/protocol.py)

**Comment by dadadel** [comment]
Hi @spotlesstofu,
Thanks for reporting. This issue is addressed by the issue #90 and was fixed by the PR #91 in current master.
