### ISSUE TITLE
__doc__ is not well parsed

### ISSUE THREAD

**Issue by vallsv** [dadadel/pyment#90]
Hi.

Here is a buggy transformation using `pygment test.py` v0.3.3

It comes from a base code that i simplified to extract the problem.
On the project the function is used as decorator to auto generate documentation.

Anyway the pygment result is not anymire valid.

Hope it can help.

```
def foo():
    __doc__ = """\
    Foo"""
```

Here is the patch result
```
--- a/test.py
+++ b/test.py
@@ -1,6 +1,6 @@
 
 
 def foo():
-    __doc__ = """\
-    Foo"""
+    """__doc__ = """\
+    Foo
```

**Comment by dadadel** [comment]
Hi! thanks for reporting. I think it is not related to `__doc__`. Actually, if there are triple quotes after the function signature, the problem arise.
I'll try to fix it.

**Comment by dadadel** [comment]
@vallsv this is fixed in current master version. Can you check that your use case is addressed ?

**Comment by vallsv** [comment]
Thx
